### ISSUE TITLE
Create Pre-export checks checklist page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#117]
- [x] Create page (ask Editorial for access to their guidance)
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Rebecca approved page

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?

**Comment by naushinthomson** [comment]
@rkcook312 @JGilbert-eLife @fred-atherden I've created a page for [this](https://elifeproduction.slab.com/posts/vor-quality-checks-rik6irlg?shr=rik6irlg) now - it's very short! Let me know if there's anything else it'd be useful to cover here.

**Comment by fred-atherden** [comment]
LGTM - thanks!

**Comment by rkcook312** [comment]
Thanks @naushinthomson, all good to me

**Comment by JGilbert-eLife** [comment]
Thanks @naushinthomson !
