### ISSUE TITLE
Update Production checklist page after PRC

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#218]
- [x] Add updates to page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Rebecca approved page

### Definition of done
- [x] Team reviewed and approved page?
- [x] Add changelog to page
